<?php

namespace FlightsBundle\Repository;

/**
 * AirplaneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirplaneRepository extends \Doctrine\ORM\EntityRepository
{
}
