<?php

namespace FlightsBundle\Repository;

/**
 * AirplaneHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirplaneHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
